---
title: "ESM 244 Lab Week 2"
author: "Satie Airame"
date: "1/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)

## For PCA
library(ggfortify)

## For ggplot customization:
library(readxl) # read excel files
library(gghighlight) # highlight series or groups we specify based on values or strings
library(lubridate)
library(plotly)

# To make compound figures:
library(patchwork)
```

## Part 1: PCA with penguins

```{r}
penguin_pca <- penguins %>% 
  select(body_mass_g, ends_with("_mm")) %>% # To select several columns that all end with a particular string, e.g., _mm
  drop_na() %>% # To remove NA
  scale() %>% # To take the data and put in all on similar scales
  prcomp() # To create a PCA outcome

penguin_pca$rotation # Bring up loadings for each of the PCA, what are the loadings for the variable, e.g., rotation

# Type ?scale and ?autoplot in the Console to learn more about these functions

# Make a new dataset with the observations that exist, match the observations that were used to create this PCA biplot but still contain the other variables.

penguin_complete <- penguins %>% 
  drop_na(body_mass_g, ends_with("_mm")) # make new dataset from penguins that has the exact same observations used in the PCA but also has the other variables

autoplot(penguin_pca,
         data = penguin_complete,
         colour = "species", # use other dataset for the aesthetics 
         loadings = TRUE, # add loadings (arrows)
         loadings.label = TRUE) + # add labels for the loadings, can customize the location of labels so they don't overlap
  theme_minimal()

```

### Part 2: ggplot customization & reading in different file types

#### Read in an .xlsx file & do some wrangling

```{r}
fish_noaa <- read_excel(here("data", "foss_landings.xlsx")) %>% 
  clean_names() %>% # default to convert titles to lower snake case
  mutate(across(where(is.character), tolower)) %>% # workhorse for how to transform existing columns, mutate columns across whatever columns are a character class and covert to lowercase, across or ends_with or starts_with are helper functions
  mutate(nmfs_name = str_sub(nmfs_name, end = - 4)) %>% # string sub extracts or replaces substrings from a character vector, put in the same column (replace) 
  filter(confidentiality == "public")
```

Make a customized graph:


```{r}
fish_plot <- ggplot(data = fish_noaa, aes(x=year, y=pounds)) +
  geom_line(aes(color = nmfs_name), show.legend = FALSE) +
  theme_minimal()
fish_plot

ggplotly(fish_plot) # to create an interactive graph
# lots of overlapping lines is spaghetti plot


```

```{r}
#### Use gghighlight to highlight certain series

ggplot(data = fish_noaa, aes(x=year, y=pounds, group = nmfs_name)) +
  geom_line() +
  theme_minimal() +
  gghighlight(nmfs_name == "tunas") # to highlight tunas by itself (in black)
```

```{r}
#### Use gghighlight to highlight certain series with specific value

ggplot(data = fish_noaa, aes(x=year, y=pounds, group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) + # assumes only want to apply color scheme to the series that highlight the gghighlight specifications, still grays out the other series
  theme_minimal() +
  gghighlight(max(pounds) > 1e8) # highlight where maximum value exceeds 10^8
```

#### Read in data from URL, 'lubridate()', 'mutate()', make a graph with months in logical order

```{r}
monroe_wt <- read_csv("https://data.bloomington.in.gov/dataset/2c81cfe3-62c2-46ed-8fcf-83c1880301d1/resource/13c8f7aa-af51-4008-80a9-56415c7c931e/download/mwtp_dailyelectricity_bclear.csv") %>% 
  clean_names() 
```

```{r}
monroe_ts <- monroe_wt %>% 
  mutate(date = mdy(date)) %>% # change date column to YYYY-MM-DD
  mutate(record_month = month(date)) %>% # use month function to full month from existing date
  mutate(month_name = month.abb[record_month]) %>% # month.abb to return the abbreviation for each month from record_month
  mutate(month_name = fct_reorder(month_name, record_month)) # change or transform class of a variable, use a lot, for forcats part of tidyverse, use factor reorder to convert character to a factor and set the order based on values in another variable.

# In Console:
# class(monroe_ts$month_name) to check if character or factor or ?
# unique(monroe_ts$month_name) to displah the different names
# levels(monroe_ts$month_name) to show the order of characters based on the variable we used to order the data

ggplot(data = monroe_ts, aes(month_name, y = total_k_wh))+
  geom_jitter() # need to convert month_name to factor, and need to set factor to match number of the months, once you use fct_reorder, then the months appear in order
```
### Part 3: Compound Figures with "patchwork"

```{r}
graph_a <- ggplot(data = penguins, aes(x = body_mass_g, y = flipper_length_mm)) +
  geom_point()
graph_a

graph_b <- ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species), show.legend = FALSE)
graph_b

# patchwork puts together graphs in a single figure, built to create customizable compound figures, look at patchwork documentation
# Use | to put graphs side by side
# Use / to put graphs one over the other

graph_c <- (graph_a | graph_b) / fish_plot & theme_minimal()
graph_c

ggsave(here("fig", "graph_c_sa.png"), width = 5, height = 6) # can specify where to save the graph, specify height and width in inches, etc. check out documentation on ggsave
```




